name: '1.0$(Rev:.r)'
trigger:
- master

variables:
  buildAgentVmImage: 'windows-latest'
  serviceConnection: 'codidentity'
  resourceGroupName: 'codidentity'

pool:
  vmImage: $(buildAgentVmImage)

resources: 
  repositories:
  - repository: devops
    type: git
    name: cod/Cod.Infrastructures
    ref: master

stages:
- stage: Production
  jobs:
  - template: pipelines/jobs/GenericDotnetBuild.yml@devops
    parameters:
      projectToPublish: '**/Cod.Platform.Identity.API.Functions.csproj'

  - template: pipelines/jobs/FunctionAppInfrastructure.yml@devops
    parameters:
      azureServiceConnection: $(serviceConnection)
      resourceGroupName: $(resourceGroupName)
      appNamePrefix: 'codidentity'
      enableKeyVault: true
      enableStagingSlot: true
      allowedOrigins: '*'
      checkoutDevopsStep:
        checkout: devops

  - job: Table
    dependsOn: 
      - Infrastructure
    condition: succeeded()
    pool:
      vmImage: $(buildAgentVmImage)
    variables:
      functionAppPrincipalId: $[dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppPrincipalId']]
    steps:
    - checkout: devops
    - template: pipelines/steps/newStorageAccount.yml@devops
      parameters:
        azureServiceConnection: $(serviceConnection)
        resourceGroupName: $(resourceGroupName)
        storageAccountName: 'codidentitydb'
        contributorPrincipalId: $(functionAppPrincipalId)

  - job: Configuration
    dependsOn:
      - Infrastructure
      - Table
    condition: succeeded()
    pool:
      vmImage: $(buildAgentVmImage)
    variables:
      functionAppName: $[dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppName']]
      functionAppHostname: $[dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppHostname']]
      tableFQDN: $[dependencies.Table.outputs['newStorageAccountProperties.tableFQDN']]
      keyVaultUrl: $[dependencies.Infrastructure.outputs['infrastructureOutputs.keyVaultUrl']]
    steps:
    - checkout: none
    - task: AzureAppServiceSettings@1
      displayName: 'Update AppSettings'
      inputs:
        azureSubscription: $(serviceConnection)
        appName: $(functionAppName)
        resourceGroupName: $(resourceGroupName)
        appSettings: |
          [
            {
              "name": "StorageTableOptions:FullyQualifiedDomainName",
              "value": "$(tableFQDN)",
              "slotSetting": false
            },
            {
              "name": "IdentityServiceOptions:IDTokenPublicKey",
              "value": "-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlmuIHhRUT+IvTdTajuOEdPZ75pqJrajOyDdJqf42siofTKHCPCZqtWaftL8Jae5VMHUNCflXzm9aKTLgerAxrGyCL3BkZj/dj4KjbeFoY1Akz5EJd5qjRNtzdoqUkDsuaigJTDDhyHvdVKRHzYAJSKgiw9CLRkzyKDZAp1Fxm2xICzRoF9OfH0jv5Qn11gkMHrkVkB6nv7QD3EGS2rnDwKudjnlsvgjpoNMMNvY7EHqkuxjHdGh4Hy7M3UXl50Bft9ky3gKeCgpvVYRPXHdT6k3e+81J7liEJYdVb5taPeNf3wB8WCP8Xc7FO6vod9ziDIkJv+xqUWYtlyGZBGTBrQIDAQAB-----END PUBLIC KEY-----",
              "slotSetting": false
            },
            {
              "name": "IdentityServiceOptions:IDTokenPrivateKey",
              "value": "@Microsoft.KeyVault(SecretUri=$(keyVaultUrl)/secrets/ID-TOKEN-PRIVATE-KEY/)",
              "slotSetting": false
            },
            {
              "name": "IdentityServiceOptions:IDTokenPrivateKeyPasscode",
              "value": "@Microsoft.KeyVault(SecretUri=$(keyVaultUrl)/secrets/ID-TOKEN-PRIVATE-KEY-PASSCODE/)",
              "slotSetting": false
            },
            {
              "name": "IdentityServiceOptions:TokenValidity",
              "value": "720",
              "slotSetting": false
            }
          ]
      
  - template: pipelines/jobs/FunctionAppDeploy.yml@devops
    parameters:
      serviceConnection: $(serviceConnection)
      resourceGroupName: $(resourceGroupName)
