<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Cod.Platform.Identity.API</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cod.Platform.Identity.Abstractions" Version="2.0.14-prerelease" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.2.0" />
  </ItemGroup>

</Project>
